version: '3'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - PYTHONPATH=/app
    ports:
      - "8080:8080"  # Spark Web UI
      - "7077:7077"  # Spark Master port
    volumes:
      - ./bronze:/app/bronze
      - ./sliver:/app/sliver
      - ./ETL:/app/ETL
      - ./Storage_Data:/app/Storage_Data
    working_dir: /app/ETL
    command: spark-submit dim_fact_table.py

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"