version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - PYTHONPATH=/app
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ../datasets:/app/datasets
      - ../ETL:/app/ETL
      - ../minio.env:/app/minio.env
    working_dir: /app
    networks:
      - datawarehouse

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports:
      - "8081:8081"
    networks:
      - datawarehouse

  postgresql:
    image: postgres:14
    container_name: postgresql
    hostname: postgresql
    environment:
      - POSTGRES_USER=datawarehouse
      - POSTGRES_PASSWORD=datawarehouse
      - POSTGRES_DB=datawarehouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../gold_layer:/gold_layer
    ports:
      - "5432:5432"
    networks:
      - datawarehouse

  minio:
    image: bitnami/minio:latest
    container_name: minio
    hostname: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - datawarehouse

volumes:
  postgres_data:
  minio_data:

networks:
  datawarehouse:
    driver: bridge